### ISSUE TITLE
Implement search component

### ISSUE THREAD

**Issue by ioanat-123** [chingu-voyages/v28-geckos-team-05#12]
**__Feature Description__**
End Users need to search in the app based on ingredients and nutrients

**__Major User Stories/tasks__**
- [ ] Find recipe based on ingredients (must_have)
- [ ] Find recipe based on nutrients
- [ ] Find recipe based on diet (for simplicity I would stick with diets defined by the spoonacular - 30 possible diets) 
- [ ] Find recipes if you have an intolerance 
- [ ] Use a tag list to filter recipes (search a  recipe by tag... dessert, )
- [ ] Find a random recipe for tonight  (with get random recipes)
- [ ] BE with user authentication and options (saves dietary restrictions and other constraints by which to filter recipes)

**__Additional Considerations__**
Include anything else that may be helpful. For example, links to external resources.
