### ISSUE TITLE
Manage recipe

### ISSUE THREAD

**Issue by ioanat-123** [chingu-voyages/v28-geckos-team-05#22]
**__Feature Description__**
As an End User, when I visualize a recipe I should be able to see the steps as a checklist, to generate a shopping list, to save the recipe etc.

**__Major User Stories/tasks__**
- [ ] Visualize the steps for each recipe as a checklist. Provide a way to check each step once it's completed and advance to the next one.
- [ ] Save returned recipe to the users favorites gallery
- [ ] Generate a shopping list from a recipe
- [ ] Get substitutes of certain ingredient. Use case - I don't want to eat sugar so I look for what to eat instead to have my meal sweet.

**__Additional Considerations__**
Follow a mobile-first strategy for both design & implementation of all screens
