### ISSUE TITLE
Design a home page for the application

### ISSUE THREAD

**Issue by jdmedlock** [chingu-voyages/v28-geckos-team-05#35]
**__Task Description__**
Create a home page for the application

**__Technical Considerations__**

Subtasks:
- [ ] Review Home page to ensure all use cases are covered (e.g. user not logged in)
- [ ] Identify & design  page components
- [ ] Update Marvel with components

**__Additional Considerations__**
TBD
