### ISSUE TITLE
Create a Home page

### ISSUE THREAD

**Issue by jdmedlock** [chingu-voyages/v28-geckos-team-05#44]
**__Feature Description__**
Create a Home page that will let new users decide whether they should sign up & provide logged in users with access to app functionality

**__Major User Stories/tasks__**
- [ ] Create a navigation bar component containing hamburger menu (mobile) or Home, About, Calendar, Favorites, Log In menu items (desktop) 
- [ ] Create a Search component
- [ ] Create a Filter component to narrow the display of recipes found by the Search component
- [ ] Create a container for recipe cards located through the Search component
- [ ] Create a Footer component 

**__Additional Considerations__**
Include anything else that may be helpful. For example, links to external resources.
